name: Hugo CI

on:
  push:
    branches:
      - main
      - site

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Build
        run: hugo -t terminal/exampleSite

      - name: Deploy
        run: |
          echo "Personal Token: $PERSONAL_TOKEN"
          ls -l ./public
        shell: bash
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: s4ammy/s4ammy.github.io
          publish_branch: site
          publish_dir: ./public