name: Hugo CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo -t terminal/exampleSite

      - name: Deploy
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          echo "Personal Token: $PERSONAL_TOKEN"
          ls -l ./public
          uses: peaceiris/actions-gh-pages@v3
          with:
            personal_token: ${{ secrets.PERSONAL_TOKEN }}
            external_repository: s4ammy/samanthaa.github.io
            publish_branch: main
            publish_dir: ./public