name: Build and Run Hugo Site

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
        
      - name: Build and Run Hugo site
        run: hugo server --source themes/terminal/exampleSite --buildDrafts --buildFuture
        